### ISSUE TITLE
The HairSalon dataset

### ISSUE THREAD

**Issue by ResiduaLiu** [shankarsivarajan/blender_import_HairSalon#1]
Hi Shankar, 
The HairSalon dataset link seems to be invalid. Could you please share the dataset?
Thanks

**Comment by shankarsivarajan** [comment]
Please use the dataset uploaded by [iwanao731/ofxHairModel](https://github.com/iwanao731/ofxHairModel), per the resolution of the issue you opened on that repo.

**Comment by ResiduaLiu** [comment]
> Please use the dataset uploaded by [iwanao731/ofxHairModel](https://github.com/iwanao731/ofxHairModel), per the resolution of the issue you opened on that repo.

Thanks for your help！
